kind: Template
apiVersion: v1
metadata:
  name: dockercoin
objects:
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    labels:
      app: hasher
      deploymentConfig: hasher
    name: hasher
  spec:
    replicas: 1
    selector:
      deploymentconfig: hasher
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: hasher
          deploymentconfig: hasher
        name: hasher
      spec:
        containers:
        - name: hasher
          image: hasher
          imagePullPolicy: Always
          ports:
          - name: hasher-http
            containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - hasher
        from:
          kind: ImageStreamTag
          name: hasher:latest
    - type: ConfigChange
