kind: Template
apiVersion: v1
metadata:
  name: dockercoin
objects:
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: rng
    labels:
      app: rng
  spec:
    triggers:
      - type: generic
        generic:
          secret: 052fc8a980b4686e
      - type: GitHub
        github:
          secret: f8e2f58321770f01
      - type: ImageChange
        imageChange: {}
      - type: ConfigChange
    source:
      type: Git
      git:
        uri: https://github.com/gloppasglop/openshift-dockercoin-rng.git
        ref: master
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: python:3.5
          namespace: openshift
    output:
      to:
        kind: ImageStreamTag
        name: rng:latest
- kind: ImageStream
  apiVersion: v1
  metadata:
    labels:
      app: rng
    name: rng
  spec:
    tags:
      name: latest
    dockerImageRepository: ""

