kind: Template
apiVersion: v1
metadata:
  name: dockercoin
objects:
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    labels:
      app: rng
      deploymentConfig: rng
    name: rng
  spec:
    replicas: 1
    selector:
      deploymentconfig: rng
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: rng
          deploymentconfig: rng
        name: rng
      spec:
        containers:
        - name: rng
          image: rng
          imagePullPolicy: Always
          ports:
          - name: rng-http
            containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - rng
        from:
          kind: ImageStreamTag
          name: rng:latest
    - type: ConfigChange
