kind: Template
apiVersion: v1
metadata:
  name: dockercoin
objects:
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    labels:
      app: webui
      deploymentConfig: webui
    name: webui
  spec:
    replicas: 1
    selector:
      deploymentconfig: webui
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: webui
          deploymentconfig: webui
        name: webui
      spec:
        containers:
        - name: webui
          image: webui
          imagePullPolicy: Always
          ports:
          - name: webui-http
            containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - webui
        from:
          kind: ImageStreamTag
          name: webui:latest
    - type: ConfigChange
